"""
scripts/rank.py

Person B: Active Learning Ranking Engine for LabelLess AI.

Takes predictions.json generated by Person A (YOLOv8 inference), calculates
intelligent priority scores using uncertainty, rare-class boosting, and
diversity/entropy heuristics, then outputs ranked_queue.json for:
  - Person C: Human Review Dashboard UI
  - Person D: Retraining & Experiment Pipeline (run_experiment.py)

Usage:
    python scripts/rank.py
    python scripts/rank.py --input outputs/predictions.json --output inputs/ranked_queue.json
    python scripts/rank.py --uncertainty-weight 0.7 --rare-weight 0.3
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

# Ensure UTF-8 output on Windows
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def parse_args():
    parser = argparse.ArgumentParser(
        description="Rank images for active learning review based on uncertainty and rare class priority."
    )
    parser.add_argument(
        "--input",
        "-i",
        default="outputs/predictions.json",
        help="Path to Person A's predictions.json (default: outputs/predictions.json)",
    )
    parser.add_argument(
        "--output",
        "-o",
        default="inputs/ranked_queue.json",
        help="Path to write ranked_queue.json (default: inputs/ranked_queue.json)",
    )
    parser.add_argument(
        "--uncertainty-weight",
        type=float,
        default=0.70,
        help="Weight for uncertainty component in priority score (default: 0.70)",
    )
    parser.add_argument(
        "--rare-weight",
        type=float,
        default=0.20,
        help="Weight for rare-class boost in priority score (default: 0.20)",
    )
    parser.add_argument(
        "--diversity-weight",
        type=float,
        default=0.10,
        help="Weight for diversity/entropy component in priority score (default: 0.10)",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=None,
        help="Optional: only output top K images in the queue (default: all)",
    )
    return parser.parse_args()


def calculate_class_rarity_weights(predictions: list[dict]) -> dict[str, float]:
    """Calculate inverse-frequency weights for detected classes to prioritize rare objects."""
    counts = Counter()
    for item in predictions:
        boxes = item.get("predictions") or item.get("boxes", [])
        for b in boxes:
            c = b.get("class", "unknown").lower()
            counts[c] += 1

    total_instances = sum(counts.values())
    if total_instances == 0:
        return {}

    # Inverse frequency normalized between 0.0 and 1.0
    max_count = max(counts.values())
    rarity_weights = {}
    for cls_name, count in counts.items():
        # Rare classes (low count) receive higher weight
        rarity_weights[cls_name] = round(1.0 - (count / max_count), 4)

    return rarity_weights


def score_item(
    item: dict,
    class_rarity_weights: dict[str, float],
    w_unc: float,
    w_rare: float,
    w_div: float,
) -> dict:
    """Compute active learning scores for a single image item."""
    image_id = item.get("image") or item.get("image_id", "unknown_image")
    boxes = item.get("predictions") or item.get("boxes", [])

    reasons = []

    # 1. Uncertainty Score (1.0 - confidence)
    if len(boxes) == 0:
        avg_conf = 0.0
        uncertainty_score = 1.0
        min_conf = 0.0
        reasons.append("No objects detected with sufficient confidence (high uncertainty)")
    else:
        confidences = [float(b.get("confidence", 0.0)) for b in boxes]
        avg_conf = sum(confidences) / len(confidences)
        min_conf = min(confidences)
        # Least confident prediction heavily influences uncertainty
        uncertainty_score = 0.6 * (1.0 - avg_conf) + 0.4 * (1.0 - min_conf)
        if avg_conf < 0.60:
            reasons.append(f"Low average model confidence ({avg_conf:.1%})")
        elif min_conf < 0.50:
            reasons.append(f"Uncertain detection in scene ({min_conf:.1%} confidence)")

    # 2. Rare Class Score
    rare_score = 0.0
    detected_classes = [b.get("class", "").lower() for b in boxes]
    if detected_classes:
        rarity_vals = [class_rarity_weights.get(c, 0.0) for c in detected_classes]
        rare_score = max(rarity_vals)
        rarest_cls = max(detected_classes, key=lambda c: class_rarity_weights.get(c, 0.0))
        if class_rarity_weights.get(rarest_cls, 0.0) > 0.5:
            reasons.append(f"Contains underrepresented class: {rarest_cls}")

    # 3. Diversity / Structural Entropy Score (heuristics based on multi-object density & spatial spread)
    if len(boxes) > 4:
        diversity_score = 0.85
        reasons.append(f"High scene complexity ({len(boxes)} bounding boxes)")
    elif len(boxes) > 2:
        diversity_score = 0.65
    elif len(boxes) == 0:
        diversity_score = 0.50
    else:
        diversity_score = 0.35

    # If no reasons were triggered yet, provide default
    if not reasons:
        reasons.append("Standard uncertainty queue sampling")

    # Composite Priority Score
    priority_score = (
        w_unc * uncertainty_score +
        w_rare * rare_score +
        w_div * diversity_score
    )

    # Normalize priority score to [0.0, 1.0]
    priority_score = min(1.0, max(0.0, priority_score))

    return {
        "image_id": image_id,
        "priority_score": round(priority_score, 4),
        "uncertainty_score": round(uncertainty_score, 4),
        "diversity_score": round(diversity_score, 4),
        "rare_class_score": round(rare_score, 4),
        "avg_confidence": round(avg_conf, 4),
        "detection_count": len(boxes),
        "reason": reasons[0],
        "reasons": reasons,
        "predictions": boxes,
    }


def rank_predictions(
    predictions: list[dict],
    w_unc: float = 0.70,
    w_rare: float = 0.20,
    w_div: float = 0.10,
    top_k: int | None = None,
) -> list[dict]:
    """Rank predictions from Person A to create Person B's queue."""
    rarity_weights = calculate_class_rarity_weights(predictions)

    ranked_items = [
        score_item(item, rarity_weights, w_unc, w_rare, w_div)
        for item in predictions
    ]

    # Sort descending by priority_score
    ranked_items.sort(key=lambda x: x["priority_score"], reverse=True)

    if top_k is not None:
        ranked_items = ranked_items[:top_k]

    return ranked_items


def main():
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        sys.exit(f"❌ ERROR: Input predictions file not found: {input_path}")

    print(f"📖 Reading predictions from: {input_path}")
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        sys.exit("❌ ERROR: Expected a top-level list in predictions.json")

    print(f"⚙️  Scoring {len(data)} images (Uncertainty: {args.uncertainty_weight}, Rare: {args.rare_weight}, Diversity: {args.diversity_weight}) ...")
    ranked_items = rank_predictions(
        data,
        w_unc=args.uncertainty_weight,
        w_rare=args.rare_weight,
        w_div=args.diversity_weight,
        top_k=args.top_k,
    )

    output_payload = {
        "method": "labelless",
        "total_images": len(ranked_items),
        "ranked_images": ranked_items,
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(output_payload, f, indent=2)

    print(f"✅ SUCCESS! Created {output_path} with {len(ranked_items)} prioritized images.\n")
    print("🏆 Top 5 Priority Images for Human Review:")
    for idx, item in enumerate(ranked_items[:5], 1):
        print(
            f"  {idx}. {item['image_id']} -> Priority: {item['priority_score']:.3f} "
            f"(Uncertainty: {item['uncertainty_score']:.3f}, Detections: {item['detection_count']}, "
            f"Reason: {item['reason']})"
        )


if __name__ == "__main__":
    main()
